services:
  mongodb:
    image: 'mongo:latest'
    restart: always
    environment:
#      MONGO_INITDB_ROOT_USERNAME: 'root'
#      MONGO_INITDB_ROOT_PASSWORD: 'password'
      MONGO_INITDB_DATABASE: 'activechatdb'
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db


volumes:
  dbdata: